name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:

      - name: pwd
        run: pwd

      - name: ls
        run: ls
        
      - name: Entrando na pasta
        run: cd frontend-eps-teste/frontend

      - name: Checando código
        uses: actions/checkout@v2

      - name: Setando a versão do node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Instalando dependências
        run: npm install

    #  - name: Rodando Linter
    #    run: npm run lint

      - name: Buildando o projeto
        run: npm run build
