name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Permite execução manual pelo GitHub

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checando código
        uses: actions/checkout@v2

      - name: Setando a versão do node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # Navegando para o diretório frontend
      - name: Navegando para o diretório frontend
        run: cd frontend

      # Instalando dependências
      - name: Instalando dependências
        run: npm install
        working-directory: frontend # Define o diretório de trabalho

     ## - name: Rodando Linter
     ##   run: npm run lint

      - name: Buildando o projeto
        run: npm run build
        working-directory: frontend # Define o diretório de trabalho

