name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checando código
        uses: actions/checkout@v2

      - name: Setando a versão do node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalando dependências
        run: npm install

      - name: Rodando Linter
        run: npm run lint

      - name: Buildando o projeto
        run: npm run build
